name: Creating A Tag

on:
  push:
    branches:
      - main

jobs:
  constants:
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.set_constants.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - id: set_constants
        run: |
          echo "tag_name=release_$(TZ=Asia/Tokyo date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  create_tag:
    runs-on: ubuntu-latest
    needs: [constants]
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          echo ${{ needs.constants.outputs.tag_name }}
          git tag ${{ needs.constants.outputs.tag_name }}
          git push origin ${{ needs.constants.outputs.tag_name }}
